version: '3'
services:
    web:
        build: ./
        ports: 
            - "8001:5000"
        depends_on:
            - mysql
            - redis
        environment:
            C_FORCE_ROOT: "True"
    mysql:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: hacksb
            MYSQL_DATABASE: github-monitor
        command: ['--character-set-server=utf8', '--collation-server=utf8_general_ci']
        expose:
            - "3306"
        volumes:
            - ./data/:/var/lib/mysql
    redis:
        image: redis:4
        volumes:
            - ./data_redis/:/data
